image: ubuntu:latest

stages:
  - build

build:
  stage: build
  timeout: 4 hours
  parallel:
    matrix:
      - TARGET:
          - aarch64
          - arm
          - bfin
          - i386
          - lm32
          - m68k
          - microblaze
          - mips
          - moxie
          - nios2
          - or1k
          - powerpc
          - riscv
          - sh
          - sparc
          - sparc64
          - v850
          - x86_64
  before_script:
    - apt-get -qq update
    - DEBIAN_FRONTEND=noninteractive TZ=Europe/Berlin apt-get -qq install -y
         git
         build-essential
         flex
         bison
         cmake
         texinfo
         device-tree-compiler
         u-boot-tools
         lzop
         libusb-1.0-0-dev
         python3
         python-is-python3
         libpython3-dev
         python3-dev
         unzip
  script:
    - cd rtems
    - ../source-builder/sb-set-builder \
            --log=1-$TARGET \
            --prefix=/opt/rtems/6 \
            --bset-tar-file \
            --no-install \
            6/rtems-$TARGET
  artifacts:
    name: "rsb-$TARGET"
    paths:
      - rtems/tar/*.tar*
    expire_in: 2 days
