name: CI

on:
  # Triggers the workflow on push or pull request for the given branch
  #push:
  #  branches: [ ci ]
  #pull_request:
  #  branches: [ ci ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        target:
          - arm
          - riscv
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install \
            build-essential \
            flex \
            bison \
            cmake \
            texinfo \
            device-tree-compiler \
            u-boot-tools \
            lzop \
            libusb-1.0-0-dev \
            python3 \
            python-is-python3 \
            libpython3-dev \
            python3-dev
      - name: Build toolchain
        run: |
          cd rtems
          ../source-builder/sb-set-builder \
            --log=1-${{ matrix.target }} \
            --prefix=/opt/rtems/6 \
            --bset-tar-file \
            --no-install \
            6/rtems-${{ matrix.target }}
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: rsb-${{ matrix.target }}
          path: rtems/tar/*.tar*
          retention-days: 2
